### ISSUE TITLE
Relink "Talk to an Expert" button to Drift Chat 

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#1]
mindsdb.com 
![image](https://user-images.githubusercontent.com/24927430/68886243-d8ede180-06e4-11ea-9ee0-15b4cf1857e9.png)

mindsdb.com/product
![image](https://user-images.githubusercontent.com/24927430/68886277-eacf8480-06e4-11ea-9859-3fba7d56c7c9.png)

**Comment by ZoranPandovski** [comment]
I still haven't found where drift chat should point. Will talk with mauricio

**Comment by ZoranPandovski** [comment]
@Ricram2 I am not sure what we should do with this issue?
