### ISSUE TITLE
Fix White spaces between titles (mobile)

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#10]
![IMG_69D8161DA1A6-1](https://user-images.githubusercontent.com/24927430/68892535-3c7e0c00-06f1-11ea-8635-7fd10c7f7f97.jpeg)
![IMG_46E15C6C15FA-1](https://user-images.githubusercontent.com/24927430/68892537-3c7e0c00-06f1-11ea-9284-b62113edb8a5.jpeg)
![IMG_A04E8AEADF34-1](https://user-images.githubusercontent.com/24927430/68892539-3c7e0c00-06f1-11ea-92ac-7318faa6c040.jpeg)

If needed, I could make the sketch to use as a guide. but most important for the spaces to be consistent.

**Comment by ZoranPandovski** [comment]
@Ricram2 I think we don't need sketches for this. I will add a standard margin and use it through the site.

**Comment by ZoranPandovski** [comment]
On mobile, the margin between elements is set up to be auto. Only the `Download MindsDB` button will have a bigger margin-bottom because of the hidden .gif section
