### ISSUE TITLE
Weird margin right (mobile)

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#11]
![IMG_97111BC97243-2](https://user-images.githubusercontent.com/24927430/68892748-a696b100-06f1-11ea-917f-78024226c182.jpeg)
![IMG_97111BC97243-1](https://user-images.githubusercontent.com/24927430/68892753-a8607480-06f1-11ea-994d-7e94b8101ccf.jpeg)

**Comment by Ricram2** [comment]
IphoneX

**Comment by ZoranPandovski** [comment]
There was 10 px margin added to the img logo. I have to remove it and setup as auto.

**Comment by ZoranPandovski** [comment]
![Screenshot from 2019-11-16 15-03-51](https://user-images.githubusercontent.com/7192539/68994364-834f3b80-0882-11ea-9903-9ec1a9e386ae.png)

**Comment by ZoranPandovski** [comment]
This is from iPhone X, I guess it is
![Screenshot from 2019-11-16 15-03-51](https://user-images.githubusercontent.com/7192539/68994395-c7dad700-0882-11ea-9f4c-af3ea58655cc.png)
 ok now.
