### ISSUE TITLE
Website typos

### ISSUE THREAD

**Issue by ZoranPandovski** [mindsdb/website#23]
Few very minor website typos to forward on: 

https://www.mindsdb.com/solutions/use-cases

 Under Credit Score:

“Determining which customers to give credit still is the key challenge for most financial institututions.”

Should be ‘is still’ or “to give credit to, is still”
 
Under Churn Reduction:

“Therefore, it is essential for insurers to make sure to keep customers satisfied”

Strange sentence, should probably be “to make sure they keep customers satisfied”
 

https://www.mindsdb.com/about-us

Under “Relationships come first:

‘Assest’ should be Asset
 
https://www.mindsdb.com/product

 

‘Accuarate’ should be accurate!

**Comment by Ricram2** [comment]
Image for:

> https://www.mindsdb.com/product
> 
> ‘Accuarate’ should be accurate!

![ProductTrain@3x](https://user-images.githubusercontent.com/24927430/69737423-5e6c8b00-1102-11ea-86ad-ab04437c2882.png)

**Comment by ZoranPandovski** [comment]
Done.
