### ISSUE TITLE
Add internal button for sending email to list. 

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#35]
![image](https://user-images.githubusercontent.com/24927430/71002985-5626c080-20ae-11ea-8a47-6a0e05264db7.png)

![image](https://user-images.githubusercontent.com/24927430/71003000-5e7efb80-20ae-11ea-965d-808b09e60974.png)

**Comment by ZoranPandovski** [comment]
We should ignore the whole Mailchimp form and just use the form URL, like this example https://university.webflow.com/integrations/mailchimp-form-integration
