### ISSUE TITLE
Changing text for cloning the Repo

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#37]
![image](https://user-images.githubusercontent.com/24927430/71111430-69fa2180-2197-11ea-9364-f9b804d8aa82.png)

**Comment by Ricram2** [comment]
![image](https://user-images.githubusercontent.com/24927430/71111515-a2016480-2197-11ea-9433-fc489dc753ad.png)

Add the newsletter text to the twitter paragraph like this: 

Stay up to date with all the latest news, releases and events. sign up to our newsletter and join the conversation. Follow us on Twitter

**Comment by ZoranPandovski** [comment]
From the conversation with Adam:
Lets switch it to Heading "Star our project" Button "Visit GitHub" and the  text "Visit us on GitHub and star, watch or fork our project"
