### ISSUE TITLE
Change css text style in order to avoid widows. 

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#5]
![image](https://user-images.githubusercontent.com/24927430/68887701-6fbb9d80-06e7-11ea-8595-f39d8f363ff1.png)

**Widow**: _when only one word finalizes a paragraph on a new line._

Plausible solutions:
1. Join the last two words with a non-breaking space or use.
`&nbsp`
2. Widow attribute:2  (Not widely supported by browsers)
https://css-tricks.com/almanac/properties/w/widows/

**Comment by ZoranPandovski** [comment]
![Screenshot from 2019-11-19 10-50-32](https://user-images.githubusercontent.com/7192539/69136081-83398080-0aba-11ea-9dc3-31e80bbd7a18.png)
