### ISSUE TITLE
Add GitHub Star Counter to /Opensource

### ISSUE THREAD

**Issue by AdamMCarrigan** [mindsdb/website#73]
https://buttons.github.io/

Button: Star
Show count - Yes
standard icon

<a class="github-button" href="https://github.com/mindsdb/mindsdb" data-color-scheme="no-preference: light; light: light; dark: dark;" data-size="large" data-show-count="true" aria-label="Star mindsdb/mindsdb on GitHub">Star</a>

<script async defer src="https://buttons.github.io/buttons.js"></script>

**Comment by ZoranPandovski** [comment]
Done.
