### ISSUE TITLE
Make blog main font size larger

### ISSUE THREAD

**Issue by AdamMCarrigan** [mindsdb/website#77]
A good guide is https://medium.com/ blogs

**Comment by ZoranPandovski** [comment]
Medium uses 22px but I think that would be too big for our new font. This is how it looks with 21px.
![Screenshot from 2020-01-06 14-27-52](https://user-images.githubusercontent.com/7192539/71820886-d8dce300-3090-11ea-93f7-94c71f147c4c.png)
