### ISSUE TITLE
Fix aspect ratio for scaling image

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#82]
![image](https://user-images.githubusercontent.com/24927430/71868521-6abe0d80-30dc-11ea-843d-d86bf274fae9.png)

The image should resize while keeping the same aspect ratio.

**Comment by ZoranPandovski** [comment]
This is because of the object-contain: fill property. If we set up as fit there is a right margin even if no other element adds it. I Will need to check this and find a better solution. The same issue will be on blog page.
