### ISSUE TITLE
Remove form input borders

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#84]
![image](https://user-images.githubusercontent.com/24927430/71868740-74944080-30dd-11ea-9314-59181f2d5c5a.png)

**Comment by ZoranPandovski** [comment]
This was a requirement from @AdamMCarrigan #76 . So, do we need to keep them or remove them ? @AdamMCarrigan , @Ricram2 ?

**Comment by Ricram2** [comment]
Tell you what, let’s only place the bottom border in the slate gray

**Comment by ZoranPandovski** [comment]
Ok @Ricram2

**Comment by ZoranPandovski** [comment]
I like this, it looks much better.
