### ISSUE TITLE
Fix margin on footer 

### ISSUE THREAD

**Issue by Ricram2** [mindsdb/website#89]
![image](https://user-images.githubusercontent.com/24927430/71869234-58919e80-30df-11ea-8960-f83fc8588aad.png)

Align Menu and Submenu to the right.

![image](https://user-images.githubusercontent.com/24927430/71869280-81199880-30df-11ea-97c5-2d09568bb22b.png)

**Comment by ZoranPandovski** [comment]
This is again related to the #57. Because of the shared classes, when I've changed the text fonts for #86 the font changes affects other headers. e.g #86 requires 16px font while the same in footer is 21px.
